//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarSQLiv2.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarSQLiv2.Language.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan process.
        /// </summary>
        internal static string AttackFinish1 {
            get {
                return ResourceManager.GetString("AttackFinish1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On ….
        /// </summary>
        internal static string AttackFinish2 {
            get {
                return ResourceManager.GetString("AttackFinish2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was completed in ….
        /// </summary>
        internal static string AttackFinish3 {
            get {
                return ResourceManager.GetString("AttackFinish3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for ….
        /// </summary>
        internal static string AttackStart1 {
            get {
                return ResourceManager.GetString("AttackStart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        internal static string AttackStart2 {
            get {
                return ResourceManager.GetString("AttackStart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It started at … hours..
        /// </summary>
        internal static string AttackStart3 {
            get {
                return ResourceManager.GetString("AttackStart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 Tool.
        /// </summary>
        internal static string ButtonBase64Tool {
            get {
                return ResourceManager.GetString("ButtonBase64Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ButtonCont {
            get {
                return ResourceManager.GetString("ButtonCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Base64.
        /// </summary>
        internal static string ButtonConvertBase64 {
            get {
                return ResourceManager.GetString("ButtonConvertBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonDisable {
            get {
                return ResourceManager.GetString("ButtonDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string ButtonDown {
            get {
                return ResourceManager.GetString("ButtonDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and Run.
        /// </summary>
        internal static string ButtonDownload {
            get {
                return ResourceManager.GetString("ButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ButtonEnable {
            get {
                return ResourceManager.GetString("ButtonEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonForensics {
            get {
                return ResourceManager.GetString("ButtonForensics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string ButtonRunCommand {
            get {
                return ResourceManager.GetString("ButtonRunCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run PowerShell Code.
        /// </summary>
        internal static string ButtonRunPsCommand {
            get {
                return ResourceManager.GetString("ButtonRunPsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string ButtonSelectFile {
            get {
                return ResourceManager.GetString("ButtonSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select - Import.
        /// </summary>
        internal static string ButtonSelectImport {
            get {
                return ResourceManager.GetString("ButtonSelectImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string ButtonShow {
            get {
                return ResourceManager.GetString("ButtonShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hash.
        /// </summary>
        internal static string ButtonShowHash {
            get {
                return ResourceManager.GetString("ButtonShowHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ButtonStop {
            get {
                return ResourceManager.GetString("ButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string ButtonUpload {
            get {
                return ResourceManager.GetString("ButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Users.
        /// </summary>
        internal static string CheckBoxAllUser {
            get {
                return ResourceManager.GetString("CheckBoxAllUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Logs.
        /// </summary>
        internal static string CheckBoxClearLog {
            get {
                return ResourceManager.GetString("CheckBoxClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Desktop Details.
        /// </summary>
        internal static string CheckBoxDesktop {
            get {
                return ResourceManager.GetString("CheckBoxDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get as Hex Data.
        /// </summary>
        internal static string CheckBoxHex {
            get {
                return ResourceManager.GetString("CheckBoxHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Network Card Details.
        /// </summary>
        internal static string CheckBoxNIC {
            get {
                return ResourceManager.GetString("CheckBoxNIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Operating System Details.
        /// </summary>
        internal static string CheckBoxOsDetails {
            get {
                return ResourceManager.GetString("CheckBoxOsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Command From List.
        /// </summary>
        internal static string CheckBoxSelectCommand {
            get {
                return ResourceManager.GetString("CheckBoxSelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Shares.
        /// </summary>
        internal static string CheckBoxShare {
            get {
                return ResourceManager.GetString("CheckBoxShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Windows Log Service.
        /// </summary>
        internal static string CheckBoxStopEvent {
            get {
                return ResourceManager.GetString("CheckBoxStopEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Groups.
        /// </summary>
        internal static string CheckBoxUserGroup {
            get {
                return ResourceManager.GetString("CheckBoxUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Delete Windows Event Logs.
        /// </summary>
        internal static string ComboBoxClearLog {
            get {
                return ResourceManager.GetString("ComboBoxClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete MS-SQL Logs.
        /// </summary>
        internal static string ComboBoxClearMssqlLog {
            get {
                return ResourceManager.GetString("ComboBoxClearMssqlLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Windows Log Service.
        /// </summary>
        internal static string ComboBoxStopWinEvent {
            get {
                return ResourceManager.GetString("ComboBoxStopWinEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the record of … address?.
        /// </summary>
        internal static string DeleteRecord1 {
            get {
                return ResourceManager.GetString("DeleteRecord1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has ... IP address has been removed successfully from the list..
        /// </summary>
        internal static string DeleteRecord2 {
            get {
                return ResourceManager.GetString("DeleteRecord2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   List All MS-SQL Users.
        /// </summary>
        internal static string EnumContent1 {
            get {
                return ResourceManager.GetString("EnumContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List All Databases.
        /// </summary>
        internal static string EnumContent2 {
            get {
                return ResourceManager.GetString("EnumContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List users whose password does not expire.
        /// </summary>
        internal static string EnumContent3 {
            get {
                return ResourceManager.GetString("EnumContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Available Procedure..
        /// </summary>
        internal static string EnumContent4 {
            get {
                return ResourceManager.GetString("EnumContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump the passwords of MS-SQL Users.
        /// </summary>
        internal static string EnumContent5 {
            get {
                return ResourceManager.GetString("EnumContent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Version of Operating System.
        /// </summary>
        internal static string EnumContent6 {
            get {
                return ResourceManager.GetString("EnumContent6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show The Installation Date Of The Operating System.
        /// </summary>
        internal static string EnumContent7 {
            get {
                return ResourceManager.GetString("EnumContent7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Directory Which Operating System Installed In.
        /// </summary>
        internal static string EnumContent8 {
            get {
                return ResourceManager.GetString("EnumContent8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} An error occurred during operation {0} Error {1}.
        /// </summary>
        internal static string Exception1 {
            get {
                return ResourceManager.GetString("Exception1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ….
        /// </summary>
        internal static string ExploitAddUser1 {
            get {
                return ResourceManager.GetString("ExploitAddUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to system with ... password.
        /// </summary>
        internal static string ExploitAddUser2 {
            get {
                return ResourceManager.GetString("ExploitAddUser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted, please wait….
        /// </summary>
        internal static string ExploitClearLog1 {
            get {
                return ResourceManager.GetString("ExploitClearLog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process has been completed..
        /// </summary>
        internal static string ExploitClearLog2 {
            get {
                return ResourceManager.GetString("ExploitClearLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the module you want to delete..
        /// </summary>
        internal static string ExploitError1 {
            get {
                return ResourceManager.GetString("ExploitError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid a disk..
        /// </summary>
        internal static string ExploitError2 {
            get {
                return ResourceManager.GetString("ExploitError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid directory or file!.
        /// </summary>
        internal static string ExploitError3 {
            get {
                return ResourceManager.GetString("ExploitError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventLog service has been disabled. Trying to stop service, please wait..
        /// </summary>
        internal static string ExploitEventLog1 {
            get {
                return ResourceManager.GetString("ExploitEventLog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Event Log Service is being stopped, please wait.
        /// </summary>
        internal static string ExploitEventLog2 {
            get {
                return ResourceManager.GetString("ExploitEventLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases in the MS-SQL server are being listed, please wait..
        /// </summary>
        internal static string ExploitGetDB1 {
            get {
                return ResourceManager.GetString("ExploitGetDB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a database named ….
        /// </summary>
        internal static string ExploitGetDB2 {
            get {
                return ResourceManager.GetString("ExploitGetDB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases at … are listed..
        /// </summary>
        internal static string ExploitGetDB3 {
            get {
                return ResourceManager.GetString("ExploitGetDB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a table named ….
        /// </summary>
        internal static string ExploitGetTable {
            get {
                return ResourceManager.GetString("ExploitGetTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the password file..
        /// </summary>
        internal static string FileSelectPass1 {
            get {
                return ResourceManager.GetString("FileSelectPass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password File.
        /// </summary>
        internal static string FileSelectPass2 {
            get {
                return ResourceManager.GetString("FileSelectPass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the user name file..
        /// </summary>
        internal static string FileSelectUser1 {
            get {
                return ResourceManager.GetString("FileSelectUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User File.
        /// </summary>
        internal static string FileSelectUser2 {
            get {
                return ResourceManager.GetString("FileSelectUser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Found1 {
            get {
                return ResourceManager.GetString("Found1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password of … IP address has been found … .
        /// </summary>
        internal static string Found2 {
            get {
                return ResourceManager.GetString("Found2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Found3 {
            get {
                return ResourceManager.GetString("Found3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the operation..
        /// </summary>
        internal static string GeneralError1 {
            get {
                return ResourceManager.GetString("GeneralError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurred Error.
        /// </summary>
        internal static string GeneralError2 {
            get {
                return ResourceManager.GetString("GeneralError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Search and Command Execution.
        /// </summary>
        internal static string GroupBoxAdvanced {
            get {
                return ResourceManager.GetString("GroupBoxAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string GroupBoxDatabase {
            get {
                return ResourceManager.GetString("GroupBoxDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string GroupBoxDetails {
            get {
                return ResourceManager.GetString("GroupBoxDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Directory Manager.
        /// </summary>
        internal static string GroupBoxDirectory {
            get {
                return ResourceManager.GetString("GroupBoxDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Details.
        /// </summary>
        internal static string GroupBoxLogDetails {
            get {
                return ResourceManager.GetString("GroupBoxLogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured Servers.
        /// </summary>
        internal static string GroupBoxLooted {
            get {
                return ResourceManager.GetString("GroupBoxLooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of MySQL.
        /// </summary>
        internal static string GroupBoxMySqlType {
            get {
                return ResourceManager.GetString("GroupBoxMySqlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Reverse Connection, Download Malware.
        /// </summary>
        internal static string GroupBoxReverseConnection {
            get {
                return ResourceManager.GetString("GroupBoxReverseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line - Data.
        /// </summary>
        internal static string GroupBoxRow {
            get {
                return ResourceManager.GetString("GroupBoxRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string GroupBoxTable {
            get {
                return ResourceManager.GetString("GroupBoxTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        internal static string GroupBoxUserDetail {
            get {
                return ResourceManager.GetString("GroupBoxUserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string GroupBoxUserStatus {
            get {
                return ResourceManager.GetString("GroupBoxUserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Disk List.
        /// </summary>
        internal static string GroupBoxVolume {
            get {
                return ResourceManager.GetString("GroupBoxVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command to be Encrypted.
        /// </summary>
        internal static string LabelBase64Input {
            get {
                return ResourceManager.GetString("LabelBase64Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoweShell Output.
        /// </summary>
        internal static string LabelBase64Output {
            get {
                return ResourceManager.GetString("LabelBase64Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string LabelDelay {
            get {
                return ResourceManager.GetString("LabelDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string LabelDetails {
            get {
                return ResourceManager.GetString("LabelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path to Read.
        /// </summary>
        internal static string LabelFilePath {
            get {
                return ResourceManager.GetString("LabelFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded Password.
        /// </summary>
        internal static string LabelFoundedPassword {
            get {
                return ResourceManager.GetString("LabelFoundedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Passwords.
        /// </summary>
        internal static string LabelFoundedPasswords {
            get {
                return ResourceManager.GetString("LabelFoundedPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exe Address:.
        /// </summary>
        internal static string LabelMalwareUrl {
            get {
                return ResourceManager.GetString("LabelMalwareUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        internal static string LabelPath {
            get {
                return ResourceManager.GetString("LabelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string LabelRange {
            get {
                return ResourceManager.GetString("LabelRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory to Save.
        /// </summary>
        internal static string LabelSaveLocation {
            get {
                return ResourceManager.GetString("LabelSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target IP.
        /// </summary>
        internal static string LabelSingleIp {
            get {
                return ResourceManager.GetString("LabelSingleIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target File:.
        /// </summary>
        internal static string LabelTargetFile {
            get {
                return ResourceManager.GetString("LabelTargetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique.
        /// </summary>
        internal static string LabelTechnique {
            get {
                return ResourceManager.GetString("LabelTechnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested Passwords.
        /// </summary>
        internal static string LabelTestedPass {
            get {
                return ResourceManager.GetString("LabelTestedPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        internal static string LabelTimeOut {
            get {
                return ResourceManager.GetString("LabelTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory to Upload.
        /// </summary>
        internal static string LabelUploadPath {
            get {
                return ResourceManager.GetString("LabelUploadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name:.
        /// </summary>
        internal static string LabelUserName {
            get {
                return ResourceManager.GetString("LabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an account from the &quot;obtained servers&quot; section..
        /// </summary>
        internal static string LootedFileError {
            get {
                return ResourceManager.GetString("LootedFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement.
        /// </summary>
        internal static string MenuAboutAgreement {
            get {
                return ResourceManager.GetString("MenuAboutAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploit.
        /// </summary>
        internal static string MenuExploit {
            get {
                return ResourceManager.GetString("MenuExploit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSSQL.
        /// </summary>
        internal static string MenuExploitMssql {
            get {
                return ResourceManager.GetString("MenuExploitMssql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SQL User.
        /// </summary>
        internal static string MenuExploitMssqlAddMsSqlUser {
            get {
                return ResourceManager.GetString("MenuExploitMssqlAddMsSqlUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Databases.
        /// </summary>
        internal static string MenuExploitMssqlAnalysis {
            get {
                return ResourceManager.GetString("MenuExploitMssqlAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Evidences/(Tracks).
        /// </summary>
        internal static string MenuExploitMssqlAntiForensics {
            get {
                return ResourceManager.GetString("MenuExploitMssqlAntiForensics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Manager.
        /// </summary>
        internal static string MenuExploitMssqlDirectoryManager {
            get {
                return ResourceManager.GetString("MenuExploitMssqlDirectoryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Gathering.
        /// </summary>
        internal static string menuExploitMsSqlEnumerate {
            get {
                return ResourceManager.GetString("menuExploitMsSqlEnumerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS-SQL File Upload Panel.
        /// </summary>
        internal static string menuExploitMsSqlFileUpload {
            get {
                return ResourceManager.GetString("menuExploitMsSqlFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Firewall.
        /// </summary>
        internal static string MenuExploitMssqlFirewall {
            get {
                return ResourceManager.GetString("MenuExploitMssqlFirewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean The Evidences.
        /// </summary>
        internal static string menuExploitMsSqlForensics {
            get {
                return ResourceManager.GetString("menuExploitMsSqlForensics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak.
        /// </summary>
        internal static string menuExploitMsSqlHacking {
            get {
                return ResourceManager.GetString("menuExploitMsSqlHacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Info.
        /// </summary>
        internal static string MenuExploitMssqlInfo {
            get {
                return ResourceManager.GetString("MenuExploitMssqlInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Leak.
        /// </summary>
        internal static string menuExploitMsSqlPostExploitation {
            get {
                return ResourceManager.GetString("menuExploitMsSqlPostExploitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege Escalation.
        /// </summary>
        internal static string menuExploitMsSqlPrivEsc {
            get {
                return ResourceManager.GetString("menuExploitMsSqlPrivEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Programs.
        /// </summary>
        internal static string MenuExploitMssqlProgramList {
            get {
                return ResourceManager.GetString("MenuExploitMssqlProgramList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Remote Desktop.
        /// </summary>
        internal static string MenuExploitMssqlRemote {
            get {
                return ResourceManager.GetString("MenuExploitMssqlRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Connection - Meterpreter - RAT.
        /// </summary>
        internal static string MenuExploitMssqlReverse {
            get {
                return ResourceManager.GetString("MenuExploitMssqlReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Windows Services.
        /// </summary>
        internal static string MenuExploitMssqlService {
            get {
                return ResourceManager.GetString("MenuExploitMssqlService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Local Users.
        /// </summary>
        internal static string MenuExploitMssqlShowWinUser {
            get {
                return ResourceManager.GetString("MenuExploitMssqlShowWinUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Manager.
        /// </summary>
        internal static string MenuExploitMssqlTask {
            get {
                return ResourceManager.GetString("MenuExploitMssqlTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Local(Windows) User.
        /// </summary>
        internal static string MenuExploitMssqlWinUser {
            get {
                return ResourceManager.GetString("MenuExploitMssqlWinUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL.
        /// </summary>
        internal static string MenuExploitMysql {
            get {
                return ResourceManager.GetString("MenuExploitMysql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SQL User.
        /// </summary>
        internal static string MenuExploitMysqlAddUser {
            get {
                return ResourceManager.GetString("MenuExploitMysqlAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL User Passwords.
        /// </summary>
        internal static string MenuExploitMysqlHashDump {
            get {
                return ResourceManager.GetString("MenuExploitMysqlHashDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read File from Server.
        /// </summary>
        internal static string MenuExploitMysqlReadFile {
            get {
                return ResourceManager.GetString("MenuExploitMysqlReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Connection - Meterpreter - RAT.
        /// </summary>
        internal static string MenuExploitMysqlUploadRAT {
            get {
                return ResourceManager.GetString("MenuExploitMysqlUploadRAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Web Shell to Server.
        /// </summary>
        internal static string MenuExploitMysqlWebShell {
            get {
                return ResourceManager.GetString("MenuExploitMysqlWebShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MenuFileClose {
            get {
                return ResourceManager.GetString("MenuFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Session.
        /// </summary>
        internal static string MenuFileNew {
            get {
                return ResourceManager.GetString("MenuFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string MenuFileRestart {
            get {
                return ResourceManager.GetString("MenuFileRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string MenuLanguageEnglish {
            get {
                return ResourceManager.GetString("MenuLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string MenuLanguageTurkish {
            get {
                return ResourceManager.GetString("MenuLanguageTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Selected.
        /// </summary>
        internal static string MenuViewCopy {
            get {
                return ResourceManager.GetString("MenuViewCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string MenuViewSelectAll {
            get {
                return ResourceManager.GetString("MenuViewSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Download service is being activated, please wait….
        /// </summary>
        internal static string MessageDownload1 {
            get {
                return ResourceManager.GetString("MessageDownload1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is being downloaded, please wait….
        /// </summary>
        internal static string MessageDownload2 {
            get {
                return ResourceManager.GetString("MessageDownload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malware is being run, please wait….
        /// </summary>
        internal static string MessageDownload3 {
            get {
                return ResourceManager.GetString("MessageDownload3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been downloaded, running..
        /// </summary>
        internal static string MessageDownload4 {
            get {
                return ResourceManager.GetString("MessageDownload4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to download file via Powershell has been started..
        /// </summary>
        internal static string MessageDownload5 {
            get {
                return ResourceManager.GetString("MessageDownload5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server address could not be resolved, the file could not be downloaded.
        /// </summary>
        internal static string MessageDownload6 {
            get {
                return ResourceManager.GetString("MessageDownload6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing file download technique.
        /// </summary>
        internal static string MessageDownload7 {
            get {
                return ResourceManager.GetString("MessageDownload7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Saved .
        /// </summary>
        internal static string MessageDownload8 {
            get {
                return ResourceManager.GetString("MessageDownload8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has been added to the system with password {2}..
        /// </summary>
        internal static string MessageExploit1 {
            get {
                return ResourceManager.GetString("MessageExploit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases in the MS-SQL server are being listed, please wait..
        /// </summary>
        internal static string MessageExploitAnalysis1 {
            get {
                return ResourceManager.GetString("MessageExploitAnalysis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a database named 3 which has 2 id has been found on ms sql server broadcasting on ıp address.
        /// </summary>
        internal static string MessageExploitAnalysis2 {
            get {
                return ResourceManager.GetString("MessageExploitAnalysis2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The databases at {0} &lt;&lt;&lt;&lt;&lt; {1} have been listed and ready to download &gt;&gt;&gt;&gt;&gt;.
        /// </summary>
        internal static string MessageExploitAnalysis3 {
            get {
                return ResourceManager.GetString("MessageExploitAnalysis3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a table named {0} {1} and has object id of {2} ....
        /// </summary>
        internal static string MessageExploitAnalysis4 {
            get {
                return ResourceManager.GetString("MessageExploitAnalysis4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting, please wait...
        /// </summary>
        internal static string MessageExploitAntiForensics1 {
            get {
                return ResourceManager.GetString("MessageExploitAntiForensics1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventLog service has been disabled. Trying to stop service, please wait..
        /// </summary>
        internal static string MessageExploitAntiForensics2 {
            get {
                return ResourceManager.GetString("MessageExploitAntiForensics2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Event Log service is being stopped, please wait....
        /// </summary>
        internal static string MessageExploitAntiForensics3 {
            get {
                return ResourceManager.GetString("MessageExploitAntiForensics3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the module you want to delete..
        /// </summary>
        internal static string MessageExploitAntiForensics4 {
            get {
                return ResourceManager.GetString("MessageExploitAntiForensics4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the valid disc!.
        /// </summary>
        internal static string MessageExploitDirectory1 {
            get {
                return ResourceManager.GetString("MessageExploitDirectory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid directory or file!.
        /// </summary>
        internal static string MessageExploitDirectory2 {
            get {
                return ResourceManager.GetString("MessageExploitDirectory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the IP address to be exploited from the left menu..
        /// </summary>
        internal static string MessageExploitError1 {
            get {
                return ResourceManager.GetString("MessageExploitError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows firewall has been shut down successfully..
        /// </summary>
        internal static string MessageExploitFirewall1 {
            get {
                return ResourceManager.GetString("MessageExploitFirewall1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add … user.
        /// </summary>
        internal static string MessageExploitMssqlAddUser1 {
            get {
                return ResourceManager.GetString("MessageExploitMssqlAddUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  user has been added successfully..
        /// </summary>
        internal static string MessageExploitMysqlAddUser1 {
            get {
                return ResourceManager.GetString("MessageExploitMysqlAddUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root authority assigned to user..
        /// </summary>
        internal static string MessageExploitMysqlAddUser2 {
            get {
                return ResourceManager.GetString("MessageExploitMysqlAddUser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query has been completed..
        /// </summary>
        internal static string MessageExploitMysqlAddUser3 {
            get {
                return ResourceManager.GetString("MessageExploitMysqlAddUser3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin directory is being found..
        /// </summary>
        internal static string MessageExploitMysqlMeterpreter1 {
            get {
                return ResourceManager.GetString("MessageExploitMysqlMeterpreter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file.
        /// </summary>
        internal static string MessageExploitMysqlMeterpreter2 {
            get {
                return ResourceManager.GetString("MessageExploitMysqlMeterpreter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is being written with the name WarSQLi.exe to … folder..
        /// </summary>
        internal static string MessageExploitMysqlMeterpreter3 {
            get {
                return ResourceManager.GetString("MessageExploitMysqlMeterpreter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Table is being checked..
        /// </summary>
        internal static string MessageExploitMysqlReadFile1 {
            get {
                return ResourceManager.GetString("MessageExploitMysqlReadFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary table for MySQL is being created..
        /// </summary>
        internal static string MessageExploitMysqlReadFile2 {
            get {
                return ResourceManager.GetString("MessageExploitMysqlReadFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read data is being transferred to the temporary table..
        /// </summary>
        internal static string MessageExploitMysqlReadFile3 {
            get {
                return ResourceManager.GetString("MessageExploitMysqlReadFile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is being read from temporary table..
        /// </summary>
        internal static string MessageExploitMysqlReadFile4 {
            get {
                return ResourceManager.GetString("MessageExploitMysqlReadFile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Table is being cleaned..
        /// </summary>
        internal static string MessageExploitMysqlReadFile5 {
            get {
                return ResourceManager.GetString("MessageExploitMysqlReadFile5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command has been executed successfully..
        /// </summary>
        internal static string MessageExploitMysqlReadFile6 {
            get {
                return ResourceManager.GetString("MessageExploitMysqlReadFile6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure do you want to uninstall the program?.
        /// </summary>
        internal static string MessageExploitProgramList1 {
            get {
                return ResourceManager.GetString("MessageExploitProgramList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for uninstalling of the program has been received. Trying to uninstall the program, please wait..
        /// </summary>
        internal static string MessageExploitProgramList2 {
            get {
                return ResourceManager.GetString("MessageExploitProgramList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program has been uninstalled..
        /// </summary>
        internal static string MessageExploitProgramList3 {
            get {
                return ResourceManager.GetString("MessageExploitProgramList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program could not be uninstalled..
        /// </summary>
        internal static string MessageExploitProgramList4 {
            get {
                return ResourceManager.GetString("MessageExploitProgramList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDP service has been closed..
        /// </summary>
        internal static string MessageExploitRDP1 {
            get {
                return ResourceManager.GetString("MessageExploitRDP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Download service is been activated, please wait….
        /// </summary>
        internal static string MessageExploitRevCon1 {
            get {
                return ResourceManager.GetString("MessageExploitRevCon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is being downloaded, please wait...
        /// </summary>
        internal static string MessageExploitRevCon2 {
            get {
                return ResourceManager.GetString("MessageExploitRevCon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malware is running, please wait….
        /// </summary>
        internal static string MessageExploitRevCon3 {
            get {
                return ResourceManager.GetString("MessageExploitRevCon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services are being listed, please wait....
        /// </summary>
        internal static string MessageExploitService1 {
            get {
                return ResourceManager.GetString("MessageExploitService1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services have been listed..
        /// </summary>
        internal static string MessageExploitService2 {
            get {
                return ResourceManager.GetString("MessageExploitService2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service has been stopped..
        /// </summary>
        internal static string MessageExploitService3 {
            get {
                return ResourceManager.GetString("MessageExploitService3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop the service?.
        /// </summary>
        internal static string MessageExploitService4 {
            get {
                return ResourceManager.GetString("MessageExploitService4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is being stopped, please wait....
        /// </summary>
        internal static string MessageExploitService5 {
            get {
                return ResourceManager.GetString("MessageExploitService5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes are being listed, please wait...
        /// </summary>
        internal static string MessageExploitTask1 {
            get {
                return ResourceManager.GetString("MessageExploitTask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes have been listed..
        /// </summary>
        internal static string MessageExploitTask2 {
            get {
                return ResourceManager.GetString("MessageExploitTask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop the process and its sub-tasks?.
        /// </summary>
        internal static string MessageExploitTask3 {
            get {
                return ResourceManager.GetString("MessageExploitTask3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes and its sub-tasks have been stopped..
        /// </summary>
        internal static string MessageExploitTask4 {
            get {
                return ResourceManager.GetString("MessageExploitTask4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes and its sub-tasks are being stopped, please wait….
        /// </summary>
        internal static string MessageExploitTask5 {
            get {
                return ResourceManager.GetString("MessageExploitTask5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address added.
        /// </summary>
        internal static string MessageIpAdd {
            get {
                return ResourceManager.GetString("MessageIpAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDP service has been closed..
        /// </summary>
        internal static string MessageRDP1 {
            get {
                return ResourceManager.GetString("MessageRDP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDP service has been opened..
        /// </summary>
        internal static string MessageRDP2 {
            get {
                return ResourceManager.GetString("MessageRDP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request for uninstalling of the program has been received. Trying to uninstall the program, please wait..
        /// </summary>
        internal static string MessageRemoveProgram1 {
            get {
                return ResourceManager.GetString("MessageRemoveProgram1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program has been uninstalled..
        /// </summary>
        internal static string MessageRemoveProgram2 {
            get {
                return ResourceManager.GetString("MessageRemoveProgram2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program could not be uninstalled..
        /// </summary>
        internal static string MessageRemoveProgram3 {
            get {
                return ResourceManager.GetString("MessageRemoveProgram3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run as administrator to use the application..
        /// </summary>
        internal static string MessageRunAs {
            get {
                return ResourceManager.GetString("MessageRunAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services are being listed, please wait....
        /// </summary>
        internal static string MessageService1 {
            get {
                return ResourceManager.GetString("MessageService1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services have been listed..
        /// </summary>
        internal static string MessageService2 {
            get {
                return ResourceManager.GetString("MessageService2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop the service?.
        /// </summary>
        internal static string MessageService3 {
            get {
                return ResourceManager.GetString("MessageService3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is being stopped, please wait....
        /// </summary>
        internal static string MessageService4 {
            get {
                return ResourceManager.GetString("MessageService4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service has been stopped..
        /// </summary>
        internal static string MessageService5 {
            get {
                return ResourceManager.GetString("MessageService5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   IP address MSSQL.
        /// </summary>
        internal static string MsSqlVer1 {
            get {
                return ResourceManager.GetString("MsSqlVer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It uses the … version..
        /// </summary>
        internal static string MsSqlVer2 {
            get {
                return ResourceManager.GetString("MsSqlVer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak password trial attack for MySQL started.
        /// </summary>
        internal static string MySqlAttack1 {
            get {
                return ResourceManager.GetString("MySqlAttack1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connected to the MySQL server at … IP address..
        /// </summary>
        internal static string MySqlError1 {
            get {
                return ResourceManager.GetString("MySqlError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL server at ... IP address does not allow you to connect to your MySQL server with your current IP address ....
        /// </summary>
        internal static string MySqlError2 {
            get {
                return ResourceManager.GetString("MySqlError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BITS.
        /// </summary>
        internal static string RadioBits {
            get {
                return ResourceManager.GetString("RadioBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak Password Test (Extended).
        /// </summary>
        internal static string RadioExtended {
            get {
                return ResourceManager.GetString("RadioExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak Password Test (Quick).
        /// </summary>
        internal static string RadioFast {
            get {
                return ResourceManager.GetString("RadioFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linux.
        /// </summary>
        internal static string RadioLinux {
            get {
                return ResourceManager.GetString("RadioLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell.
        /// </summary>
        internal static string RadioPs {
            get {
                return ResourceManager.GetString("RadioPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Password / User List.
        /// </summary>
        internal static string RadioStaticPass {
            get {
                return ResourceManager.GetString("RadioStaticPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static User / Password List.
        /// </summary>
        internal static string RadioStaticUser {
            get {
                return ResourceManager.GetString("RadioStaticUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List / Password List.
        /// </summary>
        internal static string RadioUserAndPass {
            get {
                return ResourceManager.GetString("RadioUserAndPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 32.
        /// </summary>
        internal static string RadioW32 {
            get {
                return ResourceManager.GetString("RadioW32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 64.
        /// </summary>
        internal static string RadioW64 {
            get {
                return ResourceManager.GetString("RadioW64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        internal static string RightMenu1 {
            get {
                return ResourceManager.GetString("RightMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure do you want to delete the record of … IP address?.
        /// </summary>
        internal static string RightMenu2 {
            get {
                return ResourceManager.GetString("RightMenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has ... IP address has been removed succesfully from the list..
        /// </summary>
        internal static string RightMenu3 {
            get {
                return ResourceManager.GetString("RightMenu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to … IP address and.
        /// </summary>
        internal static string RightMenu4 {
            get {
                return ResourceManager.GetString("RightMenu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has ... port has been removed succesfully from the list..
        /// </summary>
        internal static string RightMenu5 {
            get {
                return ResourceManager.GetString("RightMenu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure do want to delete the record of … IP address?.
        /// </summary>
        internal static string ScannerRightMenu1 {
            get {
                return ResourceManager.GetString("ScannerRightMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War of SQL Impact (WarSQLi) v2.0.
        /// </summary>
        internal static string ScannerRightMenu2 {
            get {
                return ResourceManager.GetString("ScannerRightMenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has ... IP address has been removed succesfully from the list..
        /// </summary>
        internal static string ScannerRightMenu3 {
            get {
                return ResourceManager.GetString("ScannerRightMenu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number less than 255..
        /// </summary>
        internal static string ScannerTextIP1 {
            get {
                return ResourceManager.GetString("ScannerTextIP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the IP field....
        /// </summary>
        internal static string ScannerTextIP2 {
            get {
                return ResourceManager.GetString("ScannerTextIP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the range..
        /// </summary>
        internal static string ScannerTextIP3 {
            get {
                return ResourceManager.GetString("ScannerTextIP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number less than 65535..
        /// </summary>
        internal static string ScannerTextPort1 {
            get {
                return ResourceManager.GetString("ScannerTextPort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter only numbers in the port fields..
        /// </summary>
        internal static string ScannerTextPort2 {
            get {
                return ResourceManager.GetString("ScannerTextPort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning has started, please wait..
        /// </summary>
        internal static string ScanStarted1 {
            get {
                return ResourceManager.GetString("ScanStarted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning completed.
        /// </summary>
        internal static string ScanStarted2 {
            get {
                return ResourceManager.GetString("ScanStarted2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        internal static string sqlFinderError1 {
            get {
                return ResourceManager.GetString("sqlFinderError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance names are being checked for the SQL server..
        /// </summary>
        internal static string Sqlinstance1 {
            get {
                return ResourceManager.GetString("Sqlinstance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is broadcasting with ... instance address..
        /// </summary>
        internal static string Sqlinstance2 {
            get {
                return ResourceManager.GetString("Sqlinstance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get System Information..
        /// </summary>
        internal static string SysInfoContent1 {
            get {
                return ResourceManager.GetString("SysInfoContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Network Card Details..
        /// </summary>
        internal static string SysInfoContent2 {
            get {
                return ResourceManager.GetString("SysInfoContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Desktop Details..
        /// </summary>
        internal static string SysInfoContent3 {
            get {
                return ResourceManager.GetString("SysInfoContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Users.
        /// </summary>
        internal static string SysInfoContent4 {
            get {
                return ResourceManager.GetString("SysInfoContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Groups.
        /// </summary>
        internal static string SysInfoContent5 {
            get {
                return ResourceManager.GetString("SysInfoContent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Shares.
        /// </summary>
        internal static string SysInfoContent6 {
            get {
                return ResourceManager.GetString("SysInfoContent6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Install/Uninstall.
        /// </summary>
        internal static string TitleAllPrograms {
            get {
                return ResourceManager.GetString("TitleAllPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Cleaning Panel.
        /// </summary>
        internal static string TitleAntiForensics {
            get {
                return ResourceManager.GetString("TitleAntiForensics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Base64 Encryption Panel.
        /// </summary>
        internal static string TitleBase64Encoder {
            get {
                return ResourceManager.GetString("TitleBase64Encoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File - Directory Manager.
        /// </summary>
        internal static string TitleDirectoryManager {
            get {
                return ResourceManager.GetString("TitleDirectoryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Gathering Panel.
        /// </summary>
        internal static string TitleEnumeration {
            get {
                return ResourceManager.GetString("TitleEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mimikatz Dump.
        /// </summary>
        internal static string TitleMimikatz {
            get {
                return ResourceManager.GetString("TitleMimikatz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS-SQL User Adding Panel.
        /// </summary>
        internal static string TitleMSSQLUser {
            get {
                return ResourceManager.GetString("TitleMSSQLUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Manager.
        /// </summary>
        internal static string TitlePowershell {
            get {
                return ResourceManager.GetString("TitlePowershell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilege Escalation.
        /// </summary>
        internal static string TitlePrivEsc {
            get {
                return ResourceManager.GetString("TitlePrivEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop Manager.
        /// </summary>
        internal static string TitleRDP {
            get {
                return ResourceManager.GetString("TitleRDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS-SQL File Downloading Panel.
        /// </summary>
        internal static string TitleRevConn {
            get {
                return ResourceManager.GetString("TitleRevConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS-SQL File Uploading Panel.
        /// </summary>
        internal static string TitleSendFileToMsSqlServer {
            get {
                return ResourceManager.GetString("TitleSendFileToMsSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Manager.
        /// </summary>
        internal static string TitleServiceManager {
            get {
                return ResourceManager.GetString("TitleServiceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information Display Panel.
        /// </summary>
        internal static string TitleSystemInfo {
            get {
                return ResourceManager.GetString("TitleSystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Firewall Manager.
        /// </summary>
        internal static string TitleWindowsFirewall {
            get {
                return ResourceManager.GetString("TitleWindowsFirewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Local User Adding Panel.
        /// </summary>
        internal static string TitleWindowsUserAdd {
            get {
                return ResourceManager.GetString("TitleWindowsUserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Users Listing Panel.
        /// </summary>
        internal static string TitleWindowsUserList {
            get {
                return ResourceManager.GetString("TitleWindowsUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xp_cmdshell has been activated.
        /// </summary>
        internal static string XPCmdShell1 {
            get {
                return ResourceManager.GetString("XPCmdShell1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xp_cmdshell is active.
        /// </summary>
        internal static string XPCmdShell2 {
            get {
                return ResourceManager.GetString("XPCmdShell2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xp_cmdshell is being activated.
        /// </summary>
        internal static string XPCmdShell3 {
            get {
                return ResourceManager.GetString("XPCmdShell3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to activate xp_cmdshell procedure..
        /// </summary>
        internal static string XPCmdShell4 {
            get {
                return ResourceManager.GetString("XPCmdShell4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to run the command..
        /// </summary>
        internal static string XPCmdShell5 {
            get {
                return ResourceManager.GetString("XPCmdShell5", resourceCulture);
            }
        }
    }
}
